Repository 100-hours-a-week/5-yeosa-ongi-fe, pull requests merged in 2025-05, with the labels that each got.

#13 Feature/#7 로그인
  package-lock.json
  package.json
  src/App.tsx
  src/api/auth/KakaoCallback.jsx
  src/api/auth/kakao/callback.js
  src/api/auth/login.js
  src/api/config.js
  src/pages/Home.jsx
  src/pages/LoginPage.jsx
  src/pages/Main.jsx
  src/pages/auth/KakaoCallback.jsx
  src/stores/store.jsx
Labels: Feature

#20 Feature/#18
  .gitignore
  index.html
  mock/getAlbumSummary.js
  mock/getMonthlyAlbum.js
  package-lock.json
  package.json
  src/App.tsx
  src/api/albums/albumMonthly.js
  src/api/auth/login.js
  src/api/getAlbum.js
  src/api/mock/album.jsx
  src/assets/icons/Arrow Left.png
  src/components/AlbumListHeader.jsx
  src/components/AlbumThumbnail.jsx
  src/components/Card.jsx
  src/components/Category.jsx
  src/components/FlottingButton.jsx
  src/components/Grid.jsx
  src/components/Header.jsx
  src/components/Imgae.jsx
  src/components/Input.jsx
  src/components/Map.jsx
  src/components/Month.jsx
  src/components/Script.tsx
  src/index.css
  src/pages/Album.jsx
  src/pages/AlbumEditor.jsx
  src/pages/Home.jsx
  src/pages/Main.jsx
  src/pages/auth/KakaoCallback.jsx
  src/stores/store.jsx
  src/stores/userStore.jsx
  tailwind.config.js
  vite.config.ts
Labels: Feature

#22 Feature/#19 앨범 생성페이지 스타일 수정
  src/components/Input.jsx
  src/components/album/CreateAlbumButton.jsx
  src/pages/AlbumEditor.jsx
Labels: Feature

#23 Feature/#21
  package-lock.json
  package.json
  src/App.tsx
  src/api/albums/albumCreateApi.js
  src/api/albums/presignedUrl.js
  src/api/apiClient.js
  src/assets/cross_icon.png
  src/components/AlbumListHeader.jsx
  src/components/Grid.jsx
  src/components/Header.jsx
  src/components/Input.jsx
  src/pages/AlbumEditor.jsx
  src/pages/Home.jsx
  src/stores/userStore.jsx
Labels: Feature

#47 Deploy/#46
  vite.config.ts
Labels: Chore

#49 hotfix/#48
  src/pages/Album.jsx
Labels: BugFix

#73 Feature/#72
  src/api/albums/presignedUrl.js
  src/components/MyPage/ImageInput.jsx
  src/components/common/Header.jsx
  src/pages/Album.jsx
  src/pages/MyActivities.jsx
  src/pages/MyPage.jsx
Labels: Feature

#94 hotfix
  src/pages/AlbumEditor.jsx
Labels: Bug: Critical

#97 feat:온보딩 컴포넌트 구현
  src/components/Main/OnboardingScreen.jsx
  src/pages/Main.jsx
Labels: Feature
